services:
  mysql:
    image: mysql:8.0
    container_name: api-marketplace-mysql
    environment:
      MYSQL_DATABASE: api_marketplace
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3308"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - D:/docker_data/Api:/var/lib/mysql
