package com.marketplace.notification.email;

public enum EmailEventType {
    USER_REGISTERED,
    FIRST_LOGIN,
    API_SUBMITTED,
    API_APPROVED,
    API_REJECTED,
    SUBSCRIPTION_PURCHASED,
    SUBSCRIPTION_EXPIRING,
    SUBSCRIPTION_EXPIRED,
    SUBSCRIPTION_CANCELLED,
    API_KEY_CREATED,
    API_KEY_REGENERATED,
    API_KEY_REVOKED
}